apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: d-aim-io-tls
spec:
  secretName: wildcard-d-aim-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fibonacci.d-aim.io
  dnsNames:
    - fibonacci.d-aim.io
