apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "lfedaoui@d-aim.com"
    privateKeySecretRef:
      name: letsencrypt-prod-cert
    solvers:
      - http01:
          ingress:
            class: nginx